# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'exolnet/homebrew-deprecated'

# Binaries
brew 'awscli'
brew 'bash' # Latest Bash version
brew 'bat' # "cat" on steroids
brew 'coreutils' # Those that come with macOS are outdated
brew 'git'
brew 'gnupg2'
brew 'grep'
brew 'httpie'
brew 'hub'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'pkg-config'
brew 'trash' # Manage the Trash bin
brew 'tree' # List directories in a tree structure
brew 'unrar'
brew 'zlib' # Needed for Memcached
brew 'zsh'
brew 'zsh-completions'

# Development
brew 'mysql@5.7'
brew 'nginx'
brew 'node'
brew 'php'
brew 'php@7.3'
brew 'php@7.4'
brew 'redis'
brew 'yarn'

# Apps
cask '1password'
cask '1password-cli'
cask 'adobe-creative-cloud'
cask 'appzapper'
cask 'dbngin'
cask 'discord'
cask 'docker'
cask 'evernote'
cask 'figma'
cask 'firefox'
cask 'gpg-suite'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'insomnia'
cask 'iterm2'
cask 'little-snitch'
cask 'micro-snitch'
cask 'plex'
cask 'ray'
cask 'shimo'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'spectacle'
cask 'sublime-text'
cask 'tableplus'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'tower'
cask 'transmit'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wkhtmltopdf'
cask 'zoomus'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'

# Fonts
cask 'font-jetbrains-mono'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'

# Mac App Store
mas 'Medis', id: 1063631769
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'Tweetbot', id: 557168941
